### ISSUE TITLE
Unclear Documentation in Assignment 1

### ISSUE THREAD

**Issue by Joseph-Christman** [anthezium/CS510-Advanced-Topics-in-Concurrency#1]
> First, we'll write some code that tries to acquire a spinlock, returning 1 if it succeeds and 0 if it fails. Head over to worker.c and look for an empty function definition for int spin_try_lock(volatile uint64_t *lock). Fill in the body of the function, using lockcmpxchgq() to attempt to install the value LOCKED in the word that lock points to, which we expect to contain UNLOCKED, returning 0 if we succeeded in replacing UNLOCKED, and 1 if somebody else beat us to it and stored LOCKED at *lock.

The instructions here are contradictory. At first it says to return 1 on success (I assume that means successfully attained to lock) and 0 on failure (I assume that means someone else has the lock.) However, later on it says to return 0 if you replaced UNLOCKED, and 1 if someone else beat you to it. Judging from the tests, I'm assuming it was correct the first time. 

Feel free to correct me if I'm wrong.

**Comment by anthezium** [comment]
That is indeed a mistake.  I meant what I said the first time, and have pushed a fix.  Thanks for pointing this out.
